routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => 'QuestionController@getInfos', 'as' => 'home.get']);
Route::post('/', ['uses' => 'QuestionController@postInfos', 'as' => 'home.post']);

Route::get('Admin/home', ['uses' => 'QuestionController@listerInfosPerQ', 'as' => 'Admin.home'])->middleware('auth');
Route::get('Admin/homebis', ['uses' => 'QuestionController@listerInfosPerU', 'as' => 'Admin.homebis'])->middleware('auth');

Route::resource('Admin','AdminController')->middleware('auth');
Auth::routes(['register'=>false]);

Route::get('/logout', 'Auth\LoginController@logmeout')->name('logout');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $table = 'questionnaires';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\AdminRepository;
use App\Http\Requests\AdminCreateRequest;
use App\Http\Requests\AdminUpdateRequest;

class AdminController extends Controller
{
    protected $adminRepository;
    protected $nbrPerPage = 5;

    public function __construct(AdminRepository $adminRepository){
        $this->adminRepository = $adminRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $admin = $this->adminRepository->getPaginate($this->nbrPerPage);
        $links = $admin->render();

        return view('admin/index', compact('admin', 'links'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminCreateRequest $request)
    {
        $admin = $this->adminRepository->store($request->all());
        
        return redirect('Admin')->withOk("l'utilisateur " .$admin->name. " a été créé");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $admin = $this->adminRepository->getById($id);

        return view('admin/show', compact('admin'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $admin = $this->adminRepository->getById($id);

        return view('admin/edit',compact('admin'));
    }

    /**
     * Update the specified resource in storage.
     *s
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminUpdateRequest $request, $id)
    {
        $this->adminRepository->update($id, $request->all());

        return redirect('Admin')->withOk("L'utilisateur " .$request->input('name'). " a été modifié. ");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->adminRepository->destroy($id);

        return back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\QuestionRequest;
use App\Question;

class QuestionController extends Controller
{
    protected $nbrPerPage = 0;
    
    public function listerInfosPerQ(){
        $this->nbrPerPage = 5;
        $responses = Question::where('etat','=','1')->paginate($this->nbrPerPage);
        $links = $responses->render();  
        return view('admin/home', compact('responses','links'));
    }

    public function listerInfosPerU(){
        $this->nbrPerPage = 10;
        $responses = Question::where('etat','=','1')->paginate($this->nbrPerPage);
        $links = $responses->render();  
        return view('admin/homebis', compact('responses','links'));
    }

    public function getInfos(){
        return view('index');
    }


    public function postInfos(QuestionRequest $request)
    {
        $question = new Question;
        
        $question->reponse1 = $request->input('reponse1');
        $question->reponse2 = $request->input('reponse2');
        $question->reponse3 = $request->input('reponse3');
        $question->reponse4 = $request->input('reponse4');
        $question->reponse5 = $request->input('reponse5');
        $question->save();

        return view('confirm');
    }
}

resources/views/admin/create.blade.php
@extends('../template')
@extends('nav')


@section('head')  
    <title>CNTS|Admin|Home</title>  
    <style> body{ background: url('../assets/images/cntsinterface_admin.png'); overflow-x: hidden;} </style>
@endsection


@section('etatadmin') <a href="{!! Route('home.get') !!}"><span class="glyphicon glyphicon-off"></span> Deconnexion</a> @endsection

@section('contenu')
    <div class="animated pulse block-form-admin col-sm-offset-3 col-sm-6 ">
        <div class="panel panel-default">
            <div class="panel-heading">
                Creation d'un utilisateur 
                <a href="javascript:history.back()" class="btn-back-admin btn btn-primary">
                    <span class="glyphicon glyphicon-circle-arrow-left"></span>  Retour
                </a>
            </div>
            <div class="panel-body">
                {!! Form::open(['route'=>'Admin.store', 'class' => 'form-horizontal panel']) !!}
                    <div class="form-group {!! $errors->has('name') ? 'has-error animated bounce' : '' !!}">
                        {!! Form::label('name','Nom :') !!}
                        {!! Form::text('name', null, ['class'=>'form-control', 'placeholder'=>'Veuillez donner votre nom']) !!}
                        {!! $errors->first('name','<small class="help-block">:message</small>') !!}
                    </div>
                    <div class="form-group {!! $errors->has('last_name') ? 'has-error animated bounce' : '' !!}">
                        {!!  Form::label('last_name','Prenom :') !!}
                        {!! Form::text('last_name', null, ['class'=>'form-control', 'placeholder'=>'Veuillez donner votre prenom']) !!}
                        {!! $errors->first('last_name','<small class="help-block">:message</small>')!!}
                    </div>
                    <div class="form-group {!! $errors->has('adresse') ? 'has-error animated bounce' : '' !!}">
                        {!!  Form::label('adresse','Adresse :') !!}
                        {!! Form::text('adresse', null, ['class'=>'form-control', 'placeholder'=>'Veuillez donner votre adresse']) !!}
                        {!! $errors->first('adresse','<small class="help-block">:message</small>')!!}
                    </div>
                    <div class="form-group {!! $errors->has('telephone') ? 'has-error animated bounce' : '' !!}">
                        {!! Form::label('telephone','Telephone :') !!}
                        {!! Form::text('telephone', null, ['class'=>'form-control', 'placeholder'=>'Veuillez donner votre telephone']) !!}
                        {!! $errors->first('telephone','<small class="help-block">:message</small>')!!}
                    </div>
                    <div class="form-group {!! $errors->has('email') ? 'has-error animated bounce' : '' !!}">
                        {!! Form::label('email','Em@il :') !!}
                        {!! Form::email('email', null, ['class'=>'form-control', 'placeholder'=>'Veuillez donner votre email']) !!}
                        {!! $errors->first('email','<small class="help-block">:message</small>')!!}
                    </div>
                    <div class="form-group {!! $errors->has('password') ? 'has-error animated bounce' : '' !!}">
                        {!! Form::label('password','Mot de passe :') !!}
                        {!! Form::password('password', ['class'=>'form-control', 'placeholder'=>'Veuillez donner votre mot de passe']) !!}
                        {!! $errors->first('password','<small class="help-block">:message</small>') !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('password_confirmation','Ressaisir le mot de passe :') !!}
                        {!! Form::password('password_confirmation',['class'=>'form-control', 'placeholder'=>'Veuillez confirmer votre mot de passe']) !!}
                    </div>
                    {!! Form::submit('save', ['class'=>'btn btn-danger pull-right'] ) !!}
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/edit.blade.php
@extends('template')
@extends('nav')

@section('title') Admin|Edit @endsection

@section('head')    
    <title>CNTS|Admin|Edit</title>  
    <style> body{ background: url('../assets/images/cntsinterface_admin.png');} </style>
@endsection


@section('etatadmin') <a href="{!! Route('home.get') !!}"><span class="glyphicon glyphicon-off"></span> Deconnexion</a> @endsection

@section('contenu')

<div class="edit col-sm-offset-4 col-sm-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            Modification d'un utilisateur
            <a href="javascript:history.back()" class="btn-back-admin btn btn-primary">
                <span class="glyphicon glyphicon-circle-arrow-left"></span>  Retour
            </a>
        </div>
        {!! Form::model($admin, ['route'=> ['Admin.update', $admin->id] , 'method'=>'put'] ) !!}
            <div class="form-group {!! $errors->has('name') ? 'has-error animated bounce' : '' !!}">
                {!! Form::label('name','Nom :') !!}
                {!! Form::text('name', null, ['class'=>'form-control', 'placeholder'=>'Veuillez donner votre nom']) !!}
                {!! $errors->first('name','<small class="help-block">:message</small>') !!}
            </div>
            <div class="form-group {!! $errors->has('last_name') ? 'has-error animated bounce' : '' !!}">
                {!! Form::label('last_name','Prenom :') !!}
                {!! Form::text('last_name', null, ['class'=>'form-control', 'placeholder'=>'Veuillez donner votre prenom']) !!}
                {!! $errors->first('last_name','<small class="help-block">:message</small>')!!}
            </div>
            <div class="form-group {!! $errors->has('adresse') ? 'has-error animated bounce' : '' !!}">
                {!! Form::label('adresse','Adresse :') !!}
                {!! Form::text('adresse', null, ['class'=>'form-control', 'placeholder'=>'Veuillez donner votre adresse de domicile']) !!}
                {!! $errors->first('adresse','<small class="help-block">:message</small>')!!}
            </div>
            <div class="form-group {!! $errors->has('telephone') ? 'has-error animated bounce' : '' !!}">
                {!! Form::label('telephone','Telephone :') !!}
                {!! Form::text('telephone', null, ['class'=>'form-control', 'placeholder'=>'Veuillez donner votre numero de telephone']) !!}
                {!! $errors->first('telephone','<small class="help-block">:message</small>')!!}
            </div>
            {!! Form::submit('Envoyer',['class'=>'btn btn-primary pull-right'])!!}
        {!! Form::close() !!}
    </div>

</div>

@endsection

resources/views/admin/home.blade.php
@extends('template')
@extends('nav')

@section('head') 
    <title>CNTS|Admin|Home</title>  
    <style> body{ background: url('../assets/images/cntsinterface_admin_home.png');} </style>
@endsection


@section('etatadmin') <a href="{!! Route('home.get') !!}"><span class="glyphicon glyphicon-off"></span> Deconnexion</a>  @endsection


@section('contenu')  
<div class="home-admin">

    <div class="container">
        <h4 class="animated pulse title-admin title-width btn btn-danger"><i class="fas fa-cog fa-spin"></i> Espace Administrateur | Avis clients</h4>
        <h3 class="animated pulse"><a class="vue" href="{!! Route('Admin.homebis') !!}"><i class="fas fa-arrow-circle-right"></i> Passer a une vue par User</a></h3>
        <h4 class="animated fadeInLeft delay-1s"><a class="lien-admin" href="{!! Route('Admin.index') !!}"><i class="fas fa-user-cog"></i> Gérer vos utilisateurs</a></h4>
        <h3>Premiere Question <small>?</small></h3>
        <ul class="responsive-table">
            <li class="animated fadeInLeft table-header faster">
                <div class="col col-1">   <i class="fas fa-sort-down"></i> <i class="fas fa-user"></i> </div>
                <div class="col col-2"> <i class="fas fa-sort-down"></i></span> <i class="fas fa-clipboard-list"></i></div>
            </li>

            @foreach($responses as $response)
                <li class="table-row">
                    <div class="col col-1" data-label="id">{!! $response->id !!}</div>
                    <div class="col col-2" data-label="response">{!! $response->reponse1 !!}</div>
                </li>
            @endforeach
        </ul>
    </div>

    <div class="container">
        <h3>Seconde Question <small>?</small></h3>
        <ul class="responsive-table">
            <li class="table-header">
                <div class="col col-1">  <i class="fas fa-sort-down"></i> <i class="fas fa-user"></i> </div>
                <div class="col col-2"> <i class="fas fa-sort-down"></i></span> <i class="fas fa-clipboard-list"></i>
            </li>

            @foreach($responses as $response)
                <li class="table-row">
                    <div class="col col-1" data-label="id">{!! $response->id !!}</div>
                    <div class="col col-2" data-label="response">{!! $response->reponse2 !!}</div>
                </li>
            @endforeach
        </ul>
    </div>

    <div class="container">
        <h3>Troisieme Question <small>?</small></h3>
        <ul class="responsive-table">
            <li class="table-header">
                <div class="col col-1">  <i class="fas fa-sort-down"></i> <i class="fas fa-user"></i> </div>
                <div class="col col-2"> <i class="fas fa-sort-down"></i></span> <i class="fas fa-clipboard-list"></i>
            </li>

            @foreach($responses as $response)
                <li class="table-row">
                    <div class="col col-1" data-label="id">{!! $response->id !!}</div>
                    <div class="col col-2" data-label="response">{!! $response->reponse3 !!}</div>
                </li>
            @endforeach
        </ul>
    </div>

    <div class="container">
        <h3>Quatrieme Question <small>?</small></h3>
        <ul class="responsive-table">
            <li class="table-header">
                <div class="col col-1">  <i class="fas fa-sort-down"></i> <i class="fas fa-user"></i> </div>
                <div class="col col-2"> <i class="fas fa-sort-down"></i></span> <i class="fas fa-clipboard-list"></i>
            </li>

            @foreach($responses as $response)
                <li class="table-row">
                    <div class="col col-1" data-label="id">{!! $response->id !!}</div>
                    <div class="col col-2" data-label="response">{!! $response->reponse4 !!}</div>
                </li>
            @endforeach
        </ul>
    </div>

    <div class="container">
        <h3>Cinquieme Question <small>?</small></h3>
        <ul class="responsive-table">
            <li class="table-header">
                <div class="col col-1">  <i class="fas fa-sort-down"></i> <i class="fas fa-user"></i> </div>
                <div class="col col-2"> <i class="fas fa-sort-down"></i></span> <i class="fas fa-clipboard-list"></i>
            </li>

            @foreach($responses as $response)
                <li class="table-row">
                    <div class="col col-1" data-label="id">{!! $response->id !!}</div>
                    <div class="col col-2" data-label="response">{!! $response->reponse5 !!}</div>
                </li>
            @endforeach
        </ul>
    </div>
    <div class="pull-right">
        {!! $links !!}
    </div>
</div>
@endsection

resources/views/admin/homebis.blade.php
@extends('template')
@extends('nav')


@section('head')
    <title>CNTS|Admin|Home</title>  
    <style> body{ background: url('../assets/images/cntsinterface_admin_home.png'); } </style>
@endsection
@section('etatadmin') <a href="{!! Route('home.get') !!}"><span class="glyphicon glyphicon-off"></span> Deconnexion</a> @endsection

@section('contenu')
<div class="homebis-admin col-sm-offset-1 col-sm-10">
    <h4 class="animated pulse title-admin title-width btn btn-danger"><i class="fas fa-cog fa-spin"></i> Espace Administrateur | Avis clients</h4>
    <h3 class="animated pulse" ><a class="vue" href="{!! Route('Admin.home') !!}"><i class="fas fa-arrow-circle-right"></i> Passer a une vue par Question</a></h3>
    <h4 class="animated fadeInLeft delay-1s"><a class="lien-admin" href="{!! Route('Admin.index') !!}"><i class="fas fa-user-cog"></i> Gérer vos utilisateurs</a></h4>
    <table class="wrapper">
        <thead class="animated zoomIn">
            <th><h1>#</h1></th>
            <th><h1>&nbsp;Premiere  ?</h1></th>
            <th><h1>Seconde   ?</h1></th>
            <th><h1>Troisieme ?</h1></th>
            <th><h1>Quatrieme ?</h1></th>
            <th><h1>Cinquieme ?</h1></th>
        </thead>

        <tbody>
            @foreach($responses as $response)
                <tr>
                    <td>{!! $response->id !!}&nbsp;</td>
                    <td>{!! $response->reponse1 !!}</td>
                    <td>{!! $response->reponse2 !!}</td>
                    <td>{!! $response->reponse3 !!}</td>
                    <td>{!! $response->reponse4 !!}</td>
                    <td>{!! $response->reponse5 !!}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="pull-left">
        {!! $links !!}
    </div>
</div>
@endsection

resources/views/admin/index.blade.php
@extends('../template')
@extends('nav')

@section('head') 
    <title>CNTS|Admin|Users</title>  
    <style> body{ background: url('../assets/images/cntsinterface_admin.png'); background-repeat: no-repeat; } </style>
@endsection

@section('contenu')
<div class="animated pulse block-admin-table col-sm-offset-3 col-sm-6">
    @if (session()->has('ok'))
        <div class="alert alert-success alert-dismissible">{!! session('ok')!!}</div>
    @endif
    <h2 class="title-admin btn btn-danger"><i class="fas fa-cog fa-spin"></i> Espace Administrateur | Vue Admin</h2>
    <div class="panel panel-default">
        <div class="panel-heading"><h2 class="panel-title">Liste des utilisateurs</h2></div>
        <table class="table">
            <thead>
                <tr>
                    <td>#</td>
                    <td colspan="2"><i class="fas fa-arrow-circle-down"></i></span> Nom</td>
                    <td></td>
                    <td></td>
                    <td></td>
                <tr>
            </thead>
            <tbody>
                @foreach ($admin as $user)
                    <tr>
                        <td>{!! $user->id !!}</td>
                        <td class="text-primary">{{ $user->last_name }} {{ $user->name }}</td>
                        <td> {!! link_to_route('Admin.show', '&nbsp;Voir', [$user->id], ['class' => 'btn btn-success glyphicon glyphicon-eye-open']) !!}</td>
                        <td> {!! link_to_route('Admin.edit', '&nbsp;Modifier', [$user->id], ['class' => 'btn btn-warning glyphicon glyphicon-edit']) !!} </td>
                        <td> 
                           {!! Form::open(['method'=>'DELETE', 'route'=>['Admin.destroy', $user->id]]) !!}
                                {!! Form::submit('Supprimer', ['class' => 'btn btn-danger glyphicon glyphicon-trash', 'onclick' => 'return confirm(\'Voulez vous vraiment supprimer cette utilisateur ?\')']) !!}
                           {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    {!! link_to_route('Admin.home', '&nbsp;Retour aux questions', [], ['class' => 'btn btn-danger pull-left glyphicon glyphicon-chevron-left'] ) !!}
    {!! link_to_route('Admin.create', '&nbsp;Ajouter un utilisateur', [], ['class' => 'btn btn-primary pull-right glyphicon glyphicon-plus'] ) !!}
    <div class="pull-right">
        {!! $links !!}
    </div>
</div>
@endsection

resources/views/admin/show.blade.php
@extends('../template')
@extends('nav')

@section('head') 
    <title>CNTS|Admin|Home</title>  
    <style> body{ background: url('../assets/images/cntsinterface_admin.png');} </style>
@endsection

@section('etatadmin') <a href="{!! Route('home.get') !!}"><span class="glyphicon glyphicon-off"></span> Deconnexion</a>  @endsection

@section('contenu')
<div class="fullpage-show">
    <div class="animated bounce block-fiche-users col-sm-offset-3 col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading"> <i class="far fa-id-card"></i> Fiche d'utilisateur </div>
            <div class="panel-body">
                <div class="block-image">
                    <h1><i class="far fa-file-image"></i></h1>
                    <img src="" width="" height="">
                </div>
                <div class="block-text">
                    <p> <h2> <i class="fas fa-user-shield"></i> {!! $admin->name !!} {!! $admin->last_name !!}</h2> </p>
                    <p> <div class="address"> {!! $admin->adresse !!} <i class="fas fa-map-marker-alt"></i> </div> </p>
                    <p> <i class="fas fa-envelope"></i> <a href="mailto:{!! $admin->email !!}">{!! $admin->email !!}</a> </p>
                    <p> <i class="fas fa-mobile"></i> {!! $admin->telephone !!} </p>
                    <a class="btn btn-danger" href="{!! Route('Admin.index') !!}">Passer <span class="glyphicon glyphicon glyphicon-ok"></span> </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/confirm.blade.php
@extends('template')

@section('head')
    <style> body{ background: url('../assets/images/background_confirm.png'); background-size:cover;} </style>
@endsection

@section('contenu')
    <div class="animated slideInLeft confirm col-sm-offset-2 col-sm-8">
        <div class="panel panel-danger">
            <div class="panel-heading">Reponses transmises</div>
            <div class="panel-body">
                <h2>Merci. Vos reponses ont été enregistrées avec succés ✔️</h2>
            </div>
            <div class="panel-footer">
                Encore merci de votre participation et a bientot❕<br> 
                <a href="{{Route('home.get') }}">Retour vers la page d'ajout <span class="glyphicon glyphicon-circle-arrow-left"></span></a>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>CNTS|Login</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('head')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <img src="{{ asset('assets/images/cntslogo.png') }}" width="40" height="30" alt="Marque|CNTS">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        CNTS
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>